# Generated by Django 5.0.7 on 2024-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://tse1.mm.bing.net/th/id/OIP.kz5A86qjMCk6lHYchAsRZAHaHa?rs=1&pid=ImgDetMain', max_length=500),
        ),
    ]
